# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae1615796cbd2c694f800149fd876dd1cfd6ca64266303270252917fa594b10934a6b8881da3de57565c6e84ebe6dc766bed6f71e45ae0f2aeec706b3506b481

test:
  secret_key_base: b30716d33288e1ce463708dcceec8e7b277b787361a8b2a10af6ecf1eccf540206fc4314f9243b43613cea6f1e2b43f93f996bbb31056ed5df771c499be91b2d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
